# LEARNING NUMPY


In [2]:
import numpy as np
a=np.array([1,2,4,5,6,7,])
print(a)

[1 2 4 5 6 7]


## creating array 

In [8]:
l=[]
for i in range (0,5):
    u=int(input("enter array:"))
    l.append(u)
print(np.array(l))

[2 5 5 8 2]


**dimentions in array**
1. 1 dimention created by using []
2. 2 dimention created by using [[]]
3. 3 dimention created by using [[[]]]
4. and so on 
- (.ndim) is used to find the dimention of array 
- (ndmin=x) is used to make n numbers of array

In [10]:
n=np.array([1,4,5,6,3],ndmin=6)
print(n)
print(n.ndim)

[[[[[[1 4 5 6 3]]]]]]
6


## Data type in numpy


In [4]:
import numpy as np
a=np.array([1,23,24,7,7,])
print(a.dtype)

int64


In [5]:
c=np.array(["shubh","harry"])
print(c.dtype)

<U5


In [14]:
m=np.array([[1,2,4,5,"hii"],[2,4,5,6,"byy"]])
print(m)
print(m.dtype)

[['1' '2' '4' '5' 'hii']
 ['2' '4' '5' '6' 'byy']]
<U21


**character used to represent data type in numpy**
1. b=Boolean

2. f=Float

3. m=Time Delta

4. O=Object

5. U=Unicode String

6. i=Integer

7. u=Unsigned Integer

8. c=Complex Float

9. M=DateTime

10. S=String

11. V=A fixed chunk of memory for other types (void)


In [15]:
x=np.array([1,2,3],dtype="f")
print(x)
print(x.dtype)

[1. 2. 3.]
float32


In [17]:
x=np.array([1,2,3])
a=np.float32(x)
print(a)
print(a.dtype)

[1. 2. 3.]
float32


## List of Arithmetic Operations
1. Addition	+	add()
2. Subtraction	-	subtract()
3. Multiplication	*	multiply()
4. Division	/	divide()
5. Exponentiation	**	power()
6. Modulus	%	mod()

In [ ]:
import numpy as np

first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the + operator
result1 = first_array + second_array
print("Using the + operator:",result1) 

# using the add() function
result2 = np.add(first_array, second_array)
print("Using the add() function:",result2) 

Using the + operator: [ 3  7 11 15]
Using the add() function: [ 3  7 11 15]


## shape
- The shape() method returns the shape of an array i.e. the number of elements in each dimension.

In [2]:
a=np.array([1,2,3,4])
print(a.shape)
print(a)

(4,)
[1 2 3 4]


## Reshape
- We use the reshape() function to reshape a 1D array into a 2D array

In [1]:
import numpy as np

array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape a 1D array into a 2D array 
# with 2 rows and 4 columns
result = np.reshape(array1, (2, 4))
print(result)

[[1 3 5 7]
 [2 4 6 8]]


## Broadcasting in array
- we can perform mathematical operations on arrays of different shapes.

In [3]:
import numpy as np

# create 1-D array
array1 = np.array([1, 2, 3])

# create 2-D array
array2 = np.array([[1], [2], [3]])

# add arrays of different dimension
# size of array1 expands to match with array2
sum = array1 + array2

print(sum)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


## Numpy Array Indexing
- In NumPy, each element in an array is associated with a number. The number is known as an array index.

In [2]:
import numpy as np

array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])    # prints 1
print(array1[2])    # prints 5
print(array1[4])    # prints 9

1
5
9


## slicing
- array[start:stop:step]
1. start - index of the first element to be included in the slice
2. stop - index of the last element (exclusive)
3. step - step size between each element in the slice

In [1]:
import numpy as np

# create a 1D array 
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

# slice array1 from index 2 to index 6 (exclusive)
print(array1[2:6])  # [5 7 8 9]

# slice array1 from index 0 to index 8 (exclusive) with a step size of 2
print(array1[0:8:2])  # [1 5 8 2]

# slice array1 from index 3 up to the last element
print(array1[3:])  # [7 8 9 2 4 6]

# items from start to end
print(array1[:])   # [1 3 5 7 8 9 2 4 6]

[5 7 8 9]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]


## Numpy - Iterating Over Arrays
- NumPy provides flexible and efficient ways to iterate over arrays of any dimensionality. For a one-dimensional array, iterating is straightforward and similar to iterating over a Python list.

In [3]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Iterate over the array
for ele in arr:
    print(ele)


1
2
3
4
5


- Iteration in 2d aray


In [4]:
import numpy as np 

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterate over rows
for row in arr_2d:
    print(row)


[1 2 3]
[4 5 6]
[7 8 9]


- with indexing Iteration 

In [5]:
a=np.array([[[9,8,7,6],[1,2,3,4]]])
for i,d in np.ndenumerate(a):
    print(i,d)


(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


## View of Array in NumPy
- it doesn't owns the data.
- it's a view of the original data.

In [6]:
import numpy as np 
a=np.array([1,2,3,4])
vi=a.view()
print (a)
print (vi)

[1 2 3 4]
[1 2 3 4]


In [8]:
import numpy as np 
a=np.array([1,2,3,4])
vi=a.view()
a[1]=200
print (a)
print (vi)

[  1 200   3   4]
[  1 200   3   4]


## Copy of Array in NumPy
- the copy owns the data.
- the copy of an array is in the new array

In [10]:
import numpy as np 
a=np.array([1,2,3,4])
co=a.copy()
print (a)
print (co)

[1 2 3 4]
[1 2 3 4]


In [9]:
import numpy as np 
a=np.array([1,2,3,4])
co=a.copy()
a[1]=300
print (a)
print (co)

[  1 300   3   4]
[1 2 3 4]


## joint array
1. The concatenate function in NumPy joins two or more arrays along a specified axis. 
- Syntax:numpy.concatenate((array1, array2, ...), axis=0)
2. The stack() function of NumPy joins two or more arrays along a new axis.
- Syntax:numpy.stack(arrays, axis=0)

In [11]:
import numpy as np 

array_1 = np.array([1, 2]) 
array_2 = np.array([3, 4]) 

array_new = np.concatenate((array_1, array_2)) 
print(array_new) 


[1 2 3 4]


In [12]:
import numpy as np 

array_1 = np.array([[1, 2], [3, 4]]) 
array_2 = np.array([[5, 6], [7, 8]]) 

array_new = np.concatenate((array_1, array_2), axis=1) 
print(array_new) 


[[1 2 5 6]
 [3 4 7 8]]


In [16]:
import numpy as np 

array_1 = np.array([1, 2, 3, 4]) 
array_2 = np.array([5, 6, 7, 8]) 

array_new = np.stack((array_1, array_2), axis=1) 
d=np.hstack((array_1, array_2))
e=np.vstack((array_1, array_2))
f=np.dstack((array_1, array_2))
print(array_new)
print(d)
print(e)
print(f)


[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


## Splitting NumPy Arrays
- Splitting is reverse operation of Joining.

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


## functions in numpy
1. search 
2. search sort
3. sort
4. filter
5. unique
6. shuffle
7. resize 

In [7]:
import numpy as np
a=np.array([1,2,4,2,3,5,6,78,4])
x=np.where(a==2)
e=np.where((a/2)==0)
print(x)
print(e)

(array([1, 3]),)
(array([], dtype=int64),)


2. search sort

In [9]:
import numpy as np
a=np.array([1,2,4,2,3,5,6,78,4])
x=np.searchsorted(a,2)
e=np.searchsorted(a,5,side="right")
c=np.searchsorted(a,[2,3,5,6],side="right")
print(x)
print(e)
print(c)

1
6
[2 5 6 7]


3. sort

In [11]:
import numpy as np
a=np.array([1,2,4,2,3,5,6,78,4])
print(np.sort(a))

[ 1  2  2  3  4  4  5  6 78]


4. filter

In [17]:
a = np.array(["a", "b", "e", "f"])
b = np.array([True, False, True, False])
new = a[b]
print(new)

['a' 'e']


5. shuffle

In [21]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 87, 5, 6])
np.random.shuffle(a)
print(a)

[ 6  4  3  5  5  7  1  6 87  2]


6. unique

In [22]:
a = np.array([1, 2, 3, 4, 4, 6, 5, 6, 6, 7, 87, 5, 6])
c=np.unique(a)
print(a)

[ 1  2  3  4  4  6  5  6  6  7 87  5  6]


7. resize

In [24]:
a=np.array([1,2,3,4,5,6])
n=np.resize(a,(2,3))
print(n)

[[1 2 3]
 [4 5 6]]


8. insert

In [25]:
import numpy as np

# create an array
numbers = np.array([0, 1, 3, 4])

# insert 4 at index 2
array2 = np.insert(numbers, 2, 4)

print(array2)

[0 1 4 3 4]


In [26]:
import numpy as np

array1 = np.array([0, 1, 2, 3])
array2 = np.array([4, 5, 6, 7])

# insert values from array2 to array1 before index 2
array3 = np.insert(array1, 2, array2)

print(array3)

[0 1 4 5 6 7 2 3]


In [27]:
import numpy as np

array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([4, 5])

# insert values to an array before index 2
array3 = np.insert(array1, 2, array2)
 
print('\nInsert to 2D array at index 2\n', array3)

# insert values to an array before index 2 along axis 0
array4 = np.insert(array1, 2, array2, 0)

print('\nInsert to 2D array at row 2\n', array4)

# insert values to an array before index 2 along axis 1
array5 = np.insert(array1, 2, array2, 1)

print('\nInsert to 2D array at column 2\n', array5)


Insert to 2D array at index 2
 [0 1 4 5 2 3]

Insert to 2D array at row 2
 [[0 1]
 [2 3]
 [4 5]]

Insert to 2D array at column 2
 [[0 1 4]
 [2 3 5]]


9. delete

In [28]:
import numpy as np

array1 = np.array([0, 1, 2, 3])

# delete at index 2
array2 = np.delete(array1, 2)

print(array2)


[0 1 3]


In [29]:
import numpy as np

array1 = np.array([0, 1, 2, 3])

# delete values from array1 at index 2
newArray = np.delete(array1, 2)

print(newArray)

[0 1 3]


In [30]:
import numpy as np

array1 = np.array([[0, 1], [2, 3]])

# no axis, element at index 1 is deleted
array3 = np.delete(array1, 1)

print('Array after deleting element at index 1\n', array3)

# axis = 0, row 1 is deleted
array4 = np.delete(array1, 1, axis = 0)

print('\nArray after deleting row 1\n', array4)

# axis = 1, column 1 is deleted
array5 = np.delete(array1, 1, axis = 1)

print('\nArray after deleting column 1\n', array5)



Array after deleting element at index 1
 [0 2 3]

Array after deleting row 1
 [[0 1]]

Array after deleting column 1
 [[0]
 [2]]


## matrix
**A matrix is a two-dimensional data structure where numbers are arranged into rows and columns**

In [36]:
matrix1 = np.matrix([[1, 3], [5, 7]])
print(matrix1)

# Create a 3x3 matrix
matrix2 = np.array([[2, 3, 5],
                    [7, 14, 21],
                    [1, 3, 5]])
print(matrix2)

[[1 3]
 [5 7]]
[[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]


**matrix multipication**

In [37]:
# create two matrices
matrix1 = np.array([[1, 3], 
             		[5, 7]])
             
matrix2 = np.array([[2, 6], 
                    [4, 8]])

# calculate the dot product of the two matrices
result = np.dot(matrix1, matrix2)

print("matrix1 x matrix2: \n",result)

matrix1 x matrix2: 
 [[14 30]
 [38 86]]


**matrix function**

1. transpose
**The transpose of a matrix is a new matrix that is obtained by exchanging the rows and columns. For 2x2 matrix,**

In [39]:
import numpy as np

# create a matrix
matrix1 = np.array([[1, 3], 
             		[5, 7]])

# get transpose of matrix1
result = np.transpose(matrix1)

print(result)

[[1 5]
 [3 7]]


2. tnverrse
**In NumPy, we use the np.linalg.inv() function to calculate the inverse of the given matrix.**

**However, it is important to note that not all matrices have an inverse. Only square matrices that have a non-zero determinant have an inverse.**

In [40]:
import numpy as np

# create a 3x3 square matrix
matrix1 = np.array([[1, 3, 5], 
             		[7, 9, 2],
                    [4, 6, 8]])

# find inverse of matrix1
result = np.linalg.inv(matrix1)

print(result)

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]


3. Find Determinant of a Matrix in NumPy

**We can find the determinant of a square matrix using the np.linalg.det() function to calculate the determinant of the given matrix.**


In [42]:
import numpy as np

# create a matrix
matrix1 = np.array([[1, 2, 3], 
             		[4, 5, 1],
                    [2, 3, 4]])

# find determinant of matrix1
result = np.linalg.det(matrix1)

print(result)

-5.000000000000001
